### ISSUE TITLE
Where to download CrossCodeEval raw data?

### ISSUE THREAD

**Issue by keezen** [codefuse-ai/RepoFuse#6]
Hello,
I am trying to reproduce results of RepoFuse.
Your Readme mentioned "Download the CrossCodeEval dataset and the raw data from https://github.com/amazon-science/cceval"

But there is no download link for CrossCodeEval raw data in https://github.com/amazon-science/cceval. 
And I also emailed the CrossCodeEval author but received no reply.

Can you provide an available link or email of CrossCodeEval raw data for reproducing the result in RepoFuse.

**Comment by sxthunder** [comment]
Hi, you can contact zijwan@amazon.com to get CrossCodeEval raw dataset

**Comment by keezen** [comment]
> Hi, you can contact [zijwan@amazon.com](mailto:zijwan@amazon.com) to get CrossCodeEval raw dataset

Thanks for your reply~
